site_name: OSG Outreach
site_url: https://opensciencegrid.github.io/outreach/
repo_url: https://github.com/opensciencegrid/outreach/
theme:
  name: readthedocs

pages:
  - Home: 'index.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
