site_name: OSG Outreach Area
site_url: https://opensciencegrid.github.io/outreach/
repo_name: null
repo_url: null
theme:
  name: windmill
  custom_dir: theme-customizations

extra:
  article_nav_top: false

# Suppress weird JavaScript problems with development server
extra_javascript: []

markdown_extensions:
  - admonition

nav:
  - OSG Outreach Home: index.md
  - OSG School Archive: past-schools.md
